apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: openshift
  deployment:
    accessible_namespaces:
      - istio-system
      - bookinfo
    ingress:
      enabled: true
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: "false"
  installation_tag: Kiali [istio-system]
  istio_namespace: istio-system
  version: v1.65