kind: ServiceMeshControlPlane
apiVersion: maistra.io/v2
metadata:
  name: basic
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  version: v2.4
  security:
    dataPlane:
      mtls: true
    controlPlane:
      mtls: true
      tls:
        minProtocolVersion: TLSv1_2
        maxProtocolVersion: TLSv1_2
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        ecdhCurves:
          - CurveP256
          - CurveP384
  tracing:
    type: Jaeger
    sampling: 10000
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  addons:
    jaeger:
      install:
        storage:
          type: Memory
    prometheus:
      enabled: true
    kiali:
      enabled: true
    grafana:
      enabled: true
